<a href="https://colab.research.google.com/github/Michaelmo12/learning_machine_class/blob/main/%D7%AA%D7%A8%D7%92%D7%99%D7%9C_%D7%9B%D7%99%D7%95%D7%95%D7%A0%D7%95%D7%9F_%D7%9E%D7%A1%D7%95%D7%95%D7%92%D7%99%D7%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**imports**

In [14]:
import pandas as pd
import matplotlib as plt
import numpy as np
from google.colab import drive
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Preparing the data**

In [16]:
dataset = pd.read_excel('/content/drive/MyDrive/winequality-red.xlsx')
dataset['quality']=dataset['quality']-2
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
results={}

**Spliting the data**

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

**Feature Scaling**

In [18]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Kernel SVM


In [19]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)#Training
y_pred = classifier.predict(X_test)#Predict

In [20]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
results['SVM']=accuracy_score(y_test, y_pred)
print(f'accuracy for kernel SVM: {results["SVM"]}')

[[  0   0   1   1   0   0]
 [  0   0  11   3   0   0]
 [  0   0 123  46   0   0]
 [  0   0  48 115   7   0]
 [  0   0   2  24  14   0]
 [  0   0   0   2   3   0]]
accuracy for kernel SVM: 0.63


#Decision Tree

In [21]:
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)#Training
y_pred = classifier.predict(X_test)#Predict

In [22]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
results['tree']=accuracy_score(y_test, y_pred)
print(f'accuracy for Decision Tree : {results["tree"]}')

[[  0   1   1   0   0   0]
 [  1   3   6   3   1   0]
 [  3  11 109  39   7   0]
 [  2   4  35 110  19   0]
 [  0   1   4  12  20   3]
 [  0   0   0   1   4   0]]
accuracy for Decision Tree : 0.605


#KNN

In [23]:
accuracies = {}
max_k = min(len(X_train), 200)  # optional limit for performance

for k in range(1, max_k):
    classifier = KNeighborsClassifier(n_neighbors=k, metric='minkowski', p=2, weights='distance')
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    accuracies[k] = accuracy_score(y_test, y_pred)
best_k=max(accuracies,key=accuracies.get)


In [24]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
results['KNN']=accuracies[best_k]
print(f'accuracy for KNN : {results["KNN"]} with a k: {best_k}')

[[  0   0   1   1   0   0]
 [  0   0  10   4   0   0]
 [  0   0 126  43   0   0]
 [  0   0  43 127   0   0]
 [  0   0   1  28  11   0]
 [  0   0   0   5   0   0]]
accuracy for KNN : 0.6875 with a k: 82


#Naive Bayes

In [25]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)#Training
y_pred = classifier.predict(X_test)#Predict

In [26]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
results['Bayes']=accuracy_score(y_test, y_pred)
print(f'accuracy for Naive Bayes : {results["Bayes"]}')

[[  0   0   1   1   0   0]
 [  0   0   8   6   0   0]
 [  3   7 110  41   8   0]
 [  0   4  42  85  34   5]
 [  1   0   0  13  23   3]
 [  0   0   0   2   3   0]]
accuracy for Naive Bayes : 0.545


# Results

In [27]:
max_model=max(results, key=results.get)
max_acc=results[max_model]
if max_model != "KNN":
  print(f'The Model with the best accuracy is {max_model} with a {max_acc} accuracy')
else:
  print(f'The Model with the best accuracy is {max_model} (using k= {best_k}) with a {max_acc} accuracy')

The Model with the best accuracy is KNN (using k= 82) with a 0.6875 accuracy
